### ISSUE TITLE
Could not find iPhone X simulator

### ISSUE THREAD

**Issue by nileshpandey3** [insiderdev/qrcode#8]
`Could not find iPhone X simulator

Error: Could not find iPhone X simulator
    at resolve (/Users/nileshpandey/Downloads/qrcode-master/node_modules/react-native/local-cli/runIOS/runIOS.js:149:13)
    at new Promise (<anonymous>)
    at runOnSimulator (/Users/nileshpandey/Downloads/qrcode-master/node_modules/react-native/local-cli/runIOS/runIOS.js:134:10)
    at Object.runIOS [as func] (/Users/nileshpandey/Downloads/qrcode-master/node_modules/react-native/local-cli/runIOS/runIOS.js:106:12)
    at Promise.resolve.then (/Users/nileshpandey/Downloads/qrcode-master/node_modules/react-native/local-cli/cliEntry.js:117:22)

error Command failed with exit code 1.`

**Comment by gaykov** [comment]
Hi, thanks for trying this out!

I suppose `Error: Could not find iPhone X simulator` means that you need to install the simulator. Did you check https://facebook.github.io/react-native/docs/getting-started.html with Native CLI? Please let me know if it helps!

Going to close the issue as it's not related to the project.
